# Generated by Django 5.0.2 on 2024-03-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_register', '0003_rename_name_user_password_remove_user_age_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
